config/routes.rb
Rails.application.routes.draw do
  resources :apps do
    resources :devices do 
      member do
        post :create, :format => :json
      end
      # curl -i -H "Content-Type: application/json" -d '{"device":{"identifier":"7757834C-D540-46A0-81A1-E4DE4B233838", "token":"71bfb7c572e7d81624c3475dd187f2909aae6377ff5e2d630e14abca818955ff", "lat":12.12312312, "lon":53.12321353, "locale":"it", "name":"Matteo Gavagnin"}}' -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices
      resources :messages do 
        # curl -i  -H "Content-Type: application/json" -d '{"message":{"title":"titolo del messaggio", "receiver_id":4}}' -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices/7757834C-D540-46A0-81A1-E4DE4B233838/messages
        member do
          # curl -i  -H "Content-Type: application/json" -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices/7757834C-D540-46A0-81A1-E4DE4B233838/messages/4/red
          post :red, :format => :json
        end
        member do
          # curl -i  -H "Content-Type: application/json" -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices/7757834C-D540-46A0-81A1-E4DE4B233838/messages/4/received
          post :received, :format => :json
        end
      end
    end
  end
  
  resources :devices  
  resources :messages

  root to: 'visitors#index'
end

# curl -i -H "Content-Type: application/json" -d '{"device":{"identifier":"7757834C-D540-46A0-81A1-E4DE4B233838", "token":"71bfb7c572e7d81624c3475dd187f2909aae6377ff5e2d630e14abca818955ff", "lat":12.12312312, "lon":53.12321353, "locale":"it", "name":"Matteo Gavagnin"}}' -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :app
  has_many  :messages
  self.primary_key = 'identifier'
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    app_id = ""
    if params[:app_id]
      @app = App.where(:identifier => params[:app_id]).first
      if @app
        app_id = @app.id
      end
    elsif params[:device][:app_id]
      @app = App.where(:identifier => params[:device][:app_id]).first
      if @app
        app_id = @app.id
      end
    end

    @device = Device.where(:identifier => params[:device][:identifier], :token => params[:device][:token], :app_id => app_id).first
    if @device
      @device.update(device_params)
    else 
      @device = Device.new(device_params)
    end
    
    @device.app_id = app_id
    @device.last_access = Time.new
    
    respond_to do |format|
      if @device.save
        format.json { render :show, status: :created, location: @device }
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
      else
        format.json { render json: @device.errors, status: :unprocessable_entity }
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:identifier, :token, :app_id, :last_access, :lat, :lon, :locale, :name)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :identifier %><br>
    <%= f.text_field :identifier, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :token %><br>
    <%= f.text_field :token, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :app_id %><br>
    <%= f.number_field :app_id, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_access %><br>
    <%= f.datetime_select :last_access, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lat %><br>
    <%= f.text_field :lat, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lon %><br>
    <%= f.text_field :lon, :class => "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :locale %><br>
    <%= f.text_field :locale, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Devices</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Identifier</th>
      <th>App</th>
      <th>Last access</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Locale</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.identifier %></td>
        <td><%= device.app_id %></td>
        <td><%= device.last_access %></td>
        <td><%= device.lat %></td>
        <td><%= device.lon %></td>
        <td><%= device.locale %></td>
        <td><%= device.name %></td>
        <td><%= link_to 'Send Message', new_message_path(:receiver_id => device.identifier), class: "btn btn-primary" , :style => "color:#fff !important;" %></td>
        <td><%= link_to 'Show', device, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_device_path(device), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", :style => "color:#fff !important;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path, class: "btn btn-primary", :style => "color:#fff !important;" %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @device.identifier %>
</p>

<p>
  <strong>Token:</strong>
  <%= @device.token %>
</p>

<p>
  <strong>App:</strong>
  <%= @device.app_id %>
</p>

<p>
  <strong>Last access:</strong>
  <%= @device.last_access %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @device.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @device.lon %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @device.locale %>
</p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>