config/routes.rb
Rails.application.routes.draw do
  resources :apps do
    resources :devices do 
      member do
        post :create, :format => :json
      end
      # curl -i -H "Content-Type: application/json" -d '{"device":{"identifier":"7757834C-D540-46A0-81A1-E4DE4B233838", "token":"71bfb7c572e7d81624c3475dd187f2909aae6377ff5e2d630e14abca818955ff", "lat":12.12312312, "lon":53.12321353, "locale":"it", "name":"Matteo Gavagnin"}}' -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices
      resources :messages do 
        # curl -i  -H "Content-Type: application/json" -d '{"message":{"title":"titolo del messaggio", "receiver_id":4}}' -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices/7757834C-D540-46A0-81A1-E4DE4B233838/messages
        member do
          # curl -i  -H "Content-Type: application/json" -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices/7757834C-D540-46A0-81A1-E4DE4B233838/messages/4/red
          post :red, :format => :json
        end
        member do
          # curl -i  -H "Content-Type: application/json" -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices/7757834C-D540-46A0-81A1-E4DE4B233838/messages/4/received
          post :received, :format => :json
        end
      end
    end
  end
  
  resources :devices  
  resources :messages

  root to: 'visitors#index'
end

# curl -i -H "Content-Type: application/json" -d '{"device":{"identifier":"7757834C-D540-46A0-81A1-E4DE4B233838", "token":"71bfb7c572e7d81624c3475dd187f2909aae6377ff5e2d630e14abca818955ff", "lat":12.12312312, "lon":53.12321353, "locale":"it", "name":"Matteo Gavagnin"}}' -X POST  http://contactlab.local:3000/apps/0c22b8e87822c825/devices

app/views/apps/_form.html.erb
<%= form_for(@app, multipart: true) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :sandbox %><br>
    <%= f.check_box :sandbox, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :certificate %><br>
    <%= f.file_field :certificate, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.text_field :password, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apps</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Key</th>
      <th>Identifier</th>
      <th>Environment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.key %></td>
        <td><%= app.identifier %></td>
        <td><%= app.environment %></td>
        <td><%= link_to 'Show', app, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_app_path(app), class: "btn btn-default"%></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", :style => "color:#fff !important;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path, class: "btn btn-primary", :style => "color:#fff !important;" %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @app.key %>
</p>

<p>
  <strong>Identifier:</strong>
  <%= @app.identifier %>
</p>

<p>
  <strong>Environment:</strong>
  <%= @app.environment %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>